Improved MarkdownViewer
QL-Win/QuickLook pull request #1490
Opened 2024-12-04 11:43 UTC by KamilDev

#### Features
- Uses the latest [github-markdown.css](https://github.com/sindresorhus/github-markdown-css/blob/main/github-markdown.css) file that contains styling support for both dark and light mode.
- Table of Contents has an improved design, and:
	- The width can be resized.
	- TOC headings are automatically highlighted to help track your position in the file.
- Improved fullscreen layout based on Github.com behavior.
- External links clicked will open in default browser instead of doing nothing.
- Uses [markdownItAnchor](https://github.com/valeriangalliat/markdown-it-anchor) to allow heading anchor links in the file to work.
- Uses [highlight.js](https://github.com/highlightjs/highlight.js) to provide syntax highlighting to codeblocks.
#### Changes
- Made changes to allow the `md2html.html` file to use relative file imports for better maintainability.
- MarkdownViewer can now easily be customized by users by modifying files in `<Quicklook data folder>/QuickLook.Plugin.MarkdownViewer/`
- Caching and `localStorage` is now supported thanks to these changes.
- Prevent default behavior of spacebar scrolling the page, while we use spacebar to dismiss the preview.
- Sets `WebView` `DefaultBackgroundColor` to prevent white flash in dark mode. After the page has loaded, sets `DefaultBackgroundColor` back to white to have the expected default behavior on HTML pages that don't specify any background color.
#### Clean up
- Removed the need for `jQuery`.
- Removed old polyfill code.

#### Screenshots
New:
![Screenshot 2024-12-04 214042](https://github.com/user-attachments/assets/1dd2e316-4192-4fd0-90f7-aea5e69ef810)

Old:
![Screenshot 2024-12-04 223338](https://github.com/user-attachments/assets/76672b37-1d1b-4e29-8b75-b8ea68f28aa2)

2024-12-05 07:39 UTC, emako requested changes

2024-12-05 07:39 UTC, emako commented on QuickLook.Plugin/QuickLook.Plugin.MarkdownViewer/Plugin.cs
> +        private void NavigationStarting_CancelNavigation(object sender, CoreWebView2NavigationStartingEventArgs e)
Can you move to class WebpagePanel?

2024-12-05 07:39 UTC, emako commented on QuickLook.Plugin/QuickLook.Plugin.MarkdownViewer/Plugin.cs
> +            _panel._webView.NavigationStarting += NavigationStarting_CancelNavigation;
This line throw an exception:
System.FieldAccessException: 方法“QuickLook.Plugin.MarkdownViewer.Plugin.View(System.String, QuickLook.Common.Plugin.ContextObject)”尝试访问字段“QuickLook.Plugin.HtmlViewer.WebpagePanel._webView”失败。
   在 QuickLook.Plugin.MarkdownViewer.Plugin.View(String path, ContextObject context) 位置 D:\Github\QuickLook\QuickLook.Plugin\QuickLook.Plugin.MarkdownViewer\Plugin.cs:行号 139
   在 QuickLook.ViewerWindow.<>c__DisplayClass6_0.<BeginShow>b__1() 位置 D:\Github\QuickLook\QuickLook\ViewerWindow.Actions.cs:行号 222
System.FieldAccessException: 方法“QuickLook.Plugin.MarkdownViewer.Plugin.View(System.String, QuickLook.Common.Plugin.ContextObject)”尝试访问字段“QuickLook.Plugin.HtmlViewer.WebpagePanel._webView”失败。
   在 QuickLook.Plugin.MarkdownViewer.Plugin.View(String path, ContextObject context) 位置 D:\Github\QuickLook\QuickLook.Plugin\QuickLook.Plugin.MarkdownViewer\Plugin.cs:行号 139
   在 QuickLook.ViewerWindow.<>c__DisplayClass6_0.<BeginShow>b__1() 位置

2024-12-05 07:39 UTC, emako commented on QuickLook.Plugin/QuickLook.Plugin.HtmlViewer/WebpagePanel.cs
> +        public Uri _currentUri;
If the new `NavigationStarting_CancelNavigation` moved to WebpagePanel, public should be restore to private.

2024-12-05 14:57 UTC, KamilDev commented on QuickLook.Plugin/QuickLook.Plugin.MarkdownViewer/Plugin.cs
> +            _panel._webView.NavigationStarting += NavigationStarting_CancelNavigation;
I'm unable to reproduce this exception. Please see if it's resolved in the newest commit.

2024-12-06 02:02 UTC, merged

2024-12-06 10:21 UTC, emako commented
@KamilDev  Could you provide some markdown file to test the code about `// Open in default browser`?

2024-12-06 11:26 UTC, KamilDev commented
Here's a test file with some links:
[example.md](https://github.com/user-attachments/files/18037373/example.md)

The Microsoft Store and Spotify links should work, for a real example. The rest are used to see that the app name associated with the URI is correct. If no app is installed that handles the URI, or it's invalid, Windows will show the native message that no app is installed to handle the URI.

The behavior should be the same when viewing .html, since the code is now in `WebpagePanel`.