Update Translations.config pt-BR
QL-Win/QuickLook pull request #968
Opened 2021-08-04 17:44 UTC by JNylson

2021-08-04 22:14 UTC, rabelux requested changes
Thank you for your contribution! Could you replace the tabs with 4 spaces so that indentation is the same in the whole document?

2021-08-05 16:19 UTC, JNylson reviewed
Fix tabs

2021-08-05 16:39 UTC, rabelux approved these changes

2021-08-15 15:32 UTC, closed without merging

2021-08-15 15:40 UTC, rabelux commented
Why did you close it?